### ISSUE TITLE
项目的主入口文件

### ISSUE THREAD

**Issue by 14709640867** [lakshyayi/react-h5-template#1]
项目的主入口文件是哪个呢？没找见index.html和main.js文件

**Comment by lakyia** [comment]
https://umijs.org/docs/guides/directory-structure 

Umi 区别于其他前端框架，没有显式的程序主入口（如 src/index.ts），所以当你有需要在应用前置、全局运行的逻辑时，优先考虑写入 global.ts 。

当你需要添加全局 Context 、修改应用运行时，请使用 [app.tsx](https://umijs.org/docs/guides/directory-structure#apptstsx) 。
